// <auto-generated />
namespace MountainTrailsWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NoPeopleArr1020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoPeopleArr1020));
        
        string IMigrationMetadata.Id
        {
            get { return "202106011739443_NoPeopleArr1020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
